version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    cooldown:
      default-days: 7
    labels:
     - "dependencies"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "10:00"
    cooldown:
      default-days: 7
      exclude:
        - "software.amazon.smithy:smithy-model"
        - "software.amazon.smithy:smithy-build"
        - "software.amazon.smithy:smithy-cli"
    labels:
     - "dependencies"
     - "no-changelog-needed"
    groups:
      gradle:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # These versions are deliberaly kept at a range that we only want to
      # update when we need to.
      - dependency-name: "software.amazon.smithy:smithy-model"
      - dependency-name: "software.amazon.smithy:smithy-build"
      - dependency-name: "software.amazon.smithy:smithy-cli"
