name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11, 17]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout smithy-gradle-plugin
        uses: actions/checkout@v2
        with:
          path: smithy-gradle-plugin

      # We checkout smithy main here since we will often require changes that
      # have not yet been released but have been merged.
      - name: Checkout smithy main branch
        uses: actions/checkout@v2
        with:
          repository: awslabs/smithy
          path: smithy

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Publish smithy main to maven local
        run: |
          cd smithy
          ./gradlew clean publishToMavenLocal

      - name: Clean and build smithy-gradle-plugin
        run: |
          cd smithy-gradle-plugin
          ./gradlew clean publishToMavenLocal
          ./gradlew -g $PWD build -Plog-tests
